# Generated by Django 5.0.4 on 2024-05-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
