# Generated by Django 4.2.7 on 2024-05-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0000_initial'),
        ('shop', '0005_alter_services_options'),
        ('shop', '0006_initial'),
    ]

    operations = [
    ]
